#!/bin/bash

generate_connector() {
  SUBREDDIT=$1

  mkdir -p conn
  cat > conn/reddit-connector-$SUBREDDIT.yaml <<EOL
apiVersion: 0.1.0
meta:
  version: 0.3.8
  name: reddit-${SUBREDDIT}
  type: http-source
  topic: reddit-posts
  producer: 
    batch-size: 10000
http:
  method: GET
  endpoint: https://www.reddit.com/r/${SUBREDDIT}/new.json
  interval: 5s
transforms:
  - uses: infinyon/jolt@0.4.1
    with:
      spec:
        - operation: shift
          spec:
            data:
              children:
                "0": 
                  data:
                    subreddit: "subreddit"
                    title: "title"
                    author: "author"
                    selftext: "selftext"
                    ups: "ups"
                    permalink: "permalink"
                    id: "id"
EOL
  echo "Connector file generated: reddit-connector-$SUBREDDIT.yaml"
}

generate_comment_connector() {
  SUBREDDIT=$1

  mkdir -p conn
  cat > conn/reddit-connector-comment-$SUBREDDIT.yaml <<EOL
apiVersion: 0.1.0
meta:
  version: 0.3.8
  name: reddit-${SUBREDDIT}-comments
  type: http-source
  topic: reddit-comments
  producer: 
    batch-size: 10000
http:
  method: GET
  endpoint: https://www.reddit.com/r/${SUBREDDIT}/comments.json
  interval: 5s
transforms:
  - uses: infinyon/jolt@0.4.1
    with:
      spec:
        - operation: shift
          spec:
            data:
              children:
                "0": 
                  data:
                    subreddit: "subreddit"
                    author: "author"
                    body: "body"
                    ups: "ups"
                    permalink: "permalink"
                    id: "id"
EOL
  echo "Connector file generated: reddit-connector-comment-$SUBREDDIT.yaml"
}


if [ -z "$1" ]; then
  echo "Usage: $0 <subreddits>"
  exit 1
fi

IFS=',' read -r -a SUBREDDITS <<< "$1"

fluvio topic create reddit-posts --retention-time 1m
fluvio topic create reddit-comments --retention-time 1m
for SUBREDDIT in "${SUBREDDITS[@]}"; do
  generate_connector "$SUBREDDIT"
  generate_comment_connector "$SUBREDDIT"
done


echo -e "--------------------\n"
echo "Making sure that http-source is installed"
if [ -e "infinyon-http-source-0.3.8.ipkg" ]; then
    echo "Package Found."
else
    echo "Package Not Found. Installing..."
    cdk hub download infinyon/http-source@0.3.8
fi

echo -e "--------------------\n"
echo "Making sure that infinyon/jolt@0.4.1 is installed"
output=$(fluvio sm list)
if echo "$output" | grep -q "infinyon/jolt@0.4.1"; then
  echo "SmartModule infinyon/jolt@0.4.1 is installed."
else
  echo "SmartModule infinyon/jolt@0.4.1 is NOT installed."
  echo "Downloading jolt"
  fluvio hub sm download infinyon/jolt@0.4.1
fi

echo -e "--------------------\n"
echo "Starting connector"
for SUBREDDIT in "${SUBREDDITS[@]}"; do
  cdk deploy start --ipkg infinyon-http-source-0.3.8.ipkg --config conn/reddit-connector-"$SUBREDDIT".yaml
  cdk deploy start --ipkg infinyon-http-source-0.3.8.ipkg --config conn/reddit-connector-comment-"$SUBREDDIT".yaml
done

